# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - default_assignees:
      - "Lctrs"
    default_reviewers:
      - "Lctrs"
    directory: "/"
    package_manager: "github_actions"
    update_schedule: "daily"
  
  - default_assignees:
      - "Lctrs"
    default_reviewers:
      - "Lctrs"
    directory: "/"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    ignored_updates:
      - match:
          dependency_name: "phpunit/phpunit"
          version_requirement: ">= 8.0.0"
